# Generated by Django 5.0.7 on 2024-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='iamge',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
