# Generated by Django 5.0.7 on 2024-07-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Influ', '0002_alter_userinfo_iamge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='profile_picture',
        ),
    ]
