# Generated by Django 5.0.7 on 2024-07-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Influ', '0003_remove_userinfo_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='iamge',
            new_name='image',
        ),
    ]
