# Generated by Django 5.0.7 on 2024-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Influ', '0005_alter_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='city',
            field=models.CharField(choices=[('casablanca', 'Casablanca'), ('rabat', 'Rabat'), ('marrakech', 'Marrakech'), ('fes', 'Fes'), ('tangier', 'Tangier'), ('agadir', 'Agadir'), ('meknes', 'Meknes'), ('oujda', 'Oujda'), ('kenitra', 'Kenitra'), ('tetouan', 'Tetouan')], default='casablanca', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profile_images',
            field=models.ImageField(blank=True, default='images/default_avatar.png', null=True, upload_to='image/'),
        ),
    ]
